version: '3'

services:
  backend:
    image: */backend:example
    build:
      context: ./backend
      args:
        # * 표시 된 매개변수들은 직접 변경해줄 부분들
        # ALLOWED_HOSTS : EC2 주소, api
        DJANGO_ALLOWED_HOSTS: * api
        DJANGO_SECRET_KEY: *
        # 백엔드와 프론트엔드 서버가 서로 다른 호스트를 사용할 경우 WHITELIST 등록
        DJANGO_CORS_ORIGIN_WHITELIST: *
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    image: */frontend:example
    build:
      context: ./frontend
      args:
        # EC2 주소
        API_URL: *
    volumes:
      - build_folder:/frontend/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  build_folder: